# ---------------------------------------------------------------------------
# ovito-auto-viz -- declarative, reproducible OVITO visualization
# https://github.com/biterik/ovito-auto-viz
# Author: Erik Bitzek <e.bitzek@mpi-susmat.de>  (ORCID 0000-0001-7430-3694)
#   1) Max-Planck-Institut for Sustainable Materials, Duesseldorf, Germany
#   2) Institute of Materials Simulation (WW8), Friedrich-Alexander-
#      Universitaet Erlangen-Nuernberg (FAU), Fuerth, Germany
# Funded by the Deutsche Forschungsgemeinschaft (DFG) -- NFDI 38/1,
# project number 460247524 (NFDI-MatWerk consortium).
# License: BSD-3-Clause (see LICENSE)
# ---------------------------------------------------------------------------
"""Write a small single-species fcc block as a LAMMPS data file.

Data-free test input for CI: no research data, no potential, no metadata.
Cube-oriented (x=[100], y=[010], z=[001]), a = 3.52 A (Ni-ish). A perfect
crystal is deliberate — PTM must classify the interior as fcc and DXA must
find zero dislocations, which is the cheapest end-to-end exercise of the
import -> PTM/DXA -> render path.

Usage: python make_fcc.py out.data [ncells]
"""
import sys

A = 3.52
BASIS = ((0.0, 0.0, 0.0), (0.5, 0.5, 0.0), (0.5, 0.0, 0.5), (0.0, 0.5, 0.5))


def main(path, n=8):
    L = n * A
    atoms = []
    for i in range(n):
        for j in range(n):
            for k in range(n):
                for bx, by, bz in BASIS:
                    atoms.append(((i + bx) * A, (j + by) * A, (k + bz) * A))
    with open(path, "w") as fh:
        fh.write("fcc test block generated by ovito-auto-viz tests/make_fcc.py\n\n")
        fh.write(f"{len(atoms)} atoms\n1 atom types\n\n")
        fh.write(f"0.0 {L:.6f} xlo xhi\n0.0 {L:.6f} ylo yhi\n0.0 {L:.6f} zlo zhi\n\n")
        fh.write("Masses\n\n1 58.6934\n\nAtoms # atomic\n\n")
        for idx, (x, y, z) in enumerate(atoms, start=1):
            fh.write(f"{idx} 1 {x:.6f} {y:.6f} {z:.6f}\n")
    print(f"wrote {path}: {len(atoms)} atoms, cubic box {L:.3f} A, a = {A} A")


if __name__ == "__main__":
    main(sys.argv[1], int(sys.argv[2]) if len(sys.argv) > 2 else 8)
