# ---------------------------------------------------------------------------
# ovito-auto-viz -- declarative, reproducible OVITO visualization
# https://github.com/biterik/ovito-auto-viz
# Author: Erik Bitzek <e.bitzek@mpi-susmat.de>  (ORCID 0000-0001-7430-3694)
#   1) Max-Planck-Institut for Sustainable Materials, Duesseldorf, Germany
#   2) Institute of Materials Simulation (WW8), Friedrich-Alexander-
#      Universitaet Erlangen-Nuernberg (FAU), Fuerth, Germany
# Funded by the Deutsche Forschungsgemeinschaft (DFG) -- NFDI 38/1,
# project number 460247524 (NFDI-MatWerk consortium).
# License: BSD-3-Clause (see LICENSE)
# ---------------------------------------------------------------------------
"""Write a small unrelaxed fcc bicrystal + its grains file, for the per-grain
tripod tests. Data-free CI fixture: no research data, no potential.

Two slabs stacked along z, joined by an exact Sigma-5 [001] twist rotation
(36.87 deg, cos = 4/5) so every orientation triplet is integer:

  lower grain (z < H):  x = [100],   y = [010],  z = [001]
  upper grain (z >= H): x = [4-30],  y = [340],  z = [001]

Unrelaxed is deliberate — this is a render/geometry fixture, not physics.
The rotation preserves z, so the two slabs never come closer than a/2
across the interface and no overlap filtering is needed. With nxy a
multiple of 5 the box edge L = nxy*a is commensurate with BOTH grains
(the box vector (5a,0,0) is the lattice vector (4a,-3a,0) of the rotated
crystal), so under periodic boundaries only the twist GBs are defective
and PTM classifies both grain interiors cleanly as fcc.

Usage: python make_bicrystal.py out.data [grains_out.yaml] [nxy] [nz]
       (defaults: <out-stem>-grains.yaml next to out.data, nxy=15, nz=8)
"""
import sys
from pathlib import Path

A = 3.52
BASIS = ((0.0, 0.0, 0.0), (0.5, 0.5, 0.0), (0.5, 0.0, 0.5), (0.0, 0.5, 0.5))
# Sigma-5 rotation: rows are the normalized crystal directions of sim x, y, z
COS, SIN = 4.0 / 5.0, 3.0 / 5.0
UPPER_X, UPPER_Y, UPPER_Z = (4, -3, 0), (3, 4, 0), (0, 0, 1)

try:
    from ovzm import YAML_CREDIT_HEADER as CREDIT
except ImportError:  # standalone use without ovzm installed
    CREDIT = ("# created with ovito-auto-viz "
              "(https://github.com/biterik/ovito-auto-viz)\n")


def lower_grain(nxy, nz):
    for i in range(nxy):
        for j in range(nxy):
            for k in range(nz):
                for bx, by, bz in BASIS:
                    yield ((i + bx) * A, (j + by) * A, (k + bz) * A)


def upper_grain(nxy, nz, H):
    lim_x = lim_y = nxy * A
    span = 2 * nxy  # generous index range: covers the box after rotation
    for i in range(-span, span):
        for j in range(-span, span):
            for k in range(nz):
                for bx, by, bz in BASIS:
                    cx, cy, cz = (i + bx) * A, (j + by) * A, (k + bz) * A
                    x = COS * cx - SIN * cy   # rotate about z by 36.87 deg
                    y = SIN * cx + COS * cy
                    if -1e-6 <= x < lim_x - 1e-6 and -1e-6 <= y < lim_y - 1e-6:
                        yield (x, y, cz + H)


def main(data_path, grains_path=None, nxy=15, nz=8):
    data_path = Path(data_path)
    if grains_path is None:
        grains_path = data_path.parent / (data_path.stem + "-grains.yaml")
    L, H = nxy * A, nz * A
    atoms = list(lower_grain(nxy, nz)) + list(upper_grain(nxy, nz, H))
    with open(data_path, "w") as fh:
        fh.write("fcc Sigma-5 [001] bicrystal generated by "
                 "ovito-auto-viz tests/make_bicrystal.py\n\n")
        fh.write(f"{len(atoms)} atoms\n1 atom types\n\n")
        fh.write(f"0.0 {L:.6f} xlo xhi\n0.0 {L:.6f} ylo yhi\n"
                 f"0.0 {2 * H:.6f} zlo zhi\n\n")
        fh.write("Masses\n\n1 58.6934\n\nAtoms # atomic\n\n")
        for idx, (x, y, z) in enumerate(atoms, start=1):
            fh.write(f"{idx} 1 {x:.6f} {y:.6f} {z:.6f}\n")
    with open(grains_path, "w") as fh:
        fh.write(CREDIT)
        fh.write("# grains file for the Sigma-5 [001] bicrystal fixture:\n"
                 "# origin in Angstrom (sim frame); x/y/z are the Miller\n"
                 "# indices, in each grain's crystal frame, of the box axes.\n"
                 "grains:\n"
                 f"  - name: lower\n"
                 f"    origin: [{L / 2:.3f}, {L / 2:.3f}, {H / 2:.3f}]\n"
                 f"    x: [1, 0, 0]\n    y: [0, 1, 0]\n    z: [0, 0, 1]\n"
                 f"  - name: upper\n"
                 f"    origin: [{L / 2:.3f}, {L / 2:.3f}, {1.5 * H:.3f}]\n"
                 f"    x: [{UPPER_X[0]}, {UPPER_X[1]}, {UPPER_X[2]}]\n"
                 f"    y: [{UPPER_Y[0]}, {UPPER_Y[1]}, {UPPER_Y[2]}]\n"
                 f"    z: [{UPPER_Z[0]}, {UPPER_Z[1]}, {UPPER_Z[2]}]\n")
    print(f"wrote {data_path}: {len(atoms)} atoms, "
          f"box {L:.2f} x {L:.2f} x {2 * H:.2f} A, a = {A} A")
    print(f"wrote {grains_path}: 2 grains (Sigma-5 [001], 36.87 deg)")


if __name__ == "__main__":
    main(sys.argv[1],
         sys.argv[2] if len(sys.argv) > 2 else None,
         int(sys.argv[3]) if len(sys.argv) > 3 else 15,
         int(sys.argv[4]) if len(sys.argv) > 4 else 8)
